#!/bin/bash

if [ -f result ];
  then
  rm result
fi
j=0

START_TIME=$SECONDS

for i in `seq 1 5`; do
    if [ -f tempresult1 ];
    then
      rm tempresult1
    fi
    python solverDraft1.py ./puzzles/p$i > tempresult1
    # python solverDraft1 -i
    diff tempresult1 ./solutions/s$i > tempcnt
    if [ -s tempcnt ] ; then
      echo "  !!Incorrect for $i th example."
    else
      echo "  Correct for $i th example."
      j=`expr $j + 1`
    fi;

    echo "==================" >> result
    echo "test" $i:  >> result
    echo "prototype:" >> result
     python solverDraft1.py ./puzzles/p$i >> result
    echo "" >>result
    echo "solution:" >> result
     cat ./solutions/s$i >> result
    echo "" >> result
done

echo " SCORE: $j / 5";

ELAPSED_TIME=$(($SECONDS - $START_TIME))
echo "Elapsed time (sec): $ELAPSED_TIME"

rm tempresult1
rm tempcnt

